# Generated by Django 4.1.5 on 2023-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.861d624cb303db96322dcaeb6ed99e9b?rik=CstlEO2%2fm6Xy4w&riu=http%3a%2f%2fthefooddisciple.com%2fwp-content%2fuploads%2f2015%2f09%2fneptune-placeholder-40.jpg&ehk=oOphLDO0j3MFugqqnhbpZY5C1OyvfNcEvqRdyVpkIzk%3d&risl=&pid=ImgRaw&r=0', max_length=500),
        ),
    ]
