# Generated by Django 4.1.5 on 2023-01-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_name', models.CharField(max_length=100)),
                ('grocery_quantity', models.CharField(max_length=100)),
                ('grocery_price', models.IntegerField()),
            ],
        ),
    ]
